data_record/urls.py
from django.urls import path

from . import views
from .views import IndexView

app_name = 'data_record'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('record/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('record/<int:record_id>/result', views.record_result, name='result'),
]

data_site/urls.py
from django.contrib import admin
from django.urls import path, include
from filebrowser.sites import site

urlpatterns = [
    path('admin/filebrowser/', site.urls),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path("data_record/", include("data_record.urls")),
]
print("location ", site.storage.location)

data_record/models.py
from django.db import models
from django.db.models.signals import post_init
import os
import glob
from .settings import DATA_BASEPATH


# Create your models here.
class Record(models.Model):
    index = models.CharField(max_length=30)
    record_date = models.DateTimeField('date recorded')
    wl_step = models.IntegerField(default=0)
    wl_start = models.IntegerField(default=0)
    wl_end = models.IntegerField(default=0)
    operator = models.CharField(max_length=30)
    datapath = models.CharField(max_length=20, default="None")
    exist = models.IntegerField(default=0)
    data_time = models.CharField(max_length=20, default="None")

    def __str__(self):
        return self.index


def extraInitForRecord(**kwargs):
    instance = kwargs.get('instance')
    datapath = os.path.join(DATA_BASEPATH, instance.index)
    if len(instance.index) > 0 and os.path.isdir(datapath):
        dirs = [os.path.join(datapath, d) for d in os.listdir(datapath)
                if os.path.isdir(os.path.join(datapath, d))
                and d[:4].isnumeric()]
        dirs.sort()
        instance.datapath = dirs[-1]
        instance.exist = 1
        instance.data_time = os.path.basename(dirs[-1])
        fns = [fn for fn in
               glob.glob(os.path.join(dirs[-1], "[0-9][0-9][0-9][0-9]_*.bmp"))]
        wls = list(set([int(os.path.basename(fn)[:4]) for fn in fns]))
        instance.wl_start = min(wls)
        instance.wl_end = max(wls)
        instance.wl_step = (instance.wl_end - instance.wl_start) // (len(wls) - 1)

    print(datapath)


post_init.connect(extraInitForRecord, Record)

data_record/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.utils import timezone
from .models import Record
import os
from .settings import DATA_BASEPATH


def index(request):
    return HttpResponse("You're looking at question ")


# Create your views here.
class IndexView(generic.ListView):
    model = Record
    template_name = 'data_record/index.html'
    context_object_name = 'latest_question_list'
    paginate_by = 1


class DetailView(generic.DetailView):
    model = Record
    template_name = 'data_record/detail.html'
    context_object_name = 'record'


def record_result(request, record_id):
    record = get_object_or_404(Record, pk=record_id)
    return HttpResponse("You're looking on record %s." % record_id)
    # return render(request, 'polls/results.html', {'question': question})

data_record/templates/data_record/detail.html
<!DOCTYPE html>
{% load static %}
<style>
 img {width: "300"}
</style>

<link rel="stylesheet" type="text/css" href="{% static 'data_record/style.css' %}" />
<h1>Data index {{record.index}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div >
    {% if record.exist == 1 %}
    <p>
        Data recorded time {{ record.data_time}}
        Calibrated with wavelength in {{record.wl_start}} ~ {{record.wl_end}} and step {{record.wl_step}}
        Uploaded by {{ record.operator }} on {{record.record_date}}
    </p>
    <p>
        {{MEDIA_ROOT}}
    </p>
    <div class="container">
        {% with 'data_record/'|add:record.index|add:'/bg.png' as image_static %}
        <img src="{% static image_static %}" alt="blank image with rectangle" id="preview">
        {% endwith %}
        <div class="topleft">
            <select id = "imgSelect" value="origin">
                <option value ="origin">origin</option>
                <option value ="blank">blank rect</option>
                <option value="locations">locations</option>
            </select>

        </div>
    </div>
    <br>
    <a href="{% url 'data_record:result' record.id %}"> Results </a>

    {% else %}
    <p>
        No available data, check record name and dataset name.
    </p>
    {% endif %}

</div>

<script>
 let imgSelect = document.getElementById('imgSelect');
 imgSelect.addEventListener("change", changeImg);

 function changeImg(){
     let imgName = imgSelect.value;
     let myImage = document.getElementById("preview");
     let image_static;
     if(imgName === 'origin') {
         image_static = 'data_record/{{record.index}}Orig.bmp';
     } else if(imgName === 'blank') {
         image_static = 'data_record/{{record.index}}blank.png';
     } else if(imgName === 'locations') {
         image_static = 'data_record/{{record.index}}mask.png';
     }
     myImage.setAttribute('src', image_static);
 }

</script>

data_record/templates/data_record/index.html
{% load static %}
<!DOCTYPE html>
<link rel="stylesheet" type="text/css" href="{% static 'data_record/style.css' %}" />

{% if latest_question_list %}
<ul>
    {% for record in latest_question_list %}
    <br>
    <li><a href="{% url 'data_record:detail' record.id %}">{{ record}}</a></li>
    {% endfor %}

</ul>
{% else %}
<p>No records are available.</p>
{% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

data_record/templates/data_record/result.html
<script src="{% static 'd3.v3.min.js' %}" charset="utf-8"></script>